from sqlalchemy import create_engine, Column, String, TIMESTAMP
from sqlalchemy.orm import declarative_base, sessionmaker
from app.config import SQLALCHEMY_DATABASE_URI

engine = create_engine(SQLALCHEMY_DATABASE_URI)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()

class Report(Base):
    __tablename__ = 'reports'

    id_atendimento = Column(String, primary_key=True, index=True)
    data_entrada = Column(TIMESTAMP)
    data_atendimento = Column(TIMESTAMP)
    data_fila = Column(TIMESTAMP)
    data_termino = Column(TIMESTAMP)
    id_tipo_integracao = Column(String)
    protocolo = Column(String)
    externo = Column(String)
    boleano_receptivo = Column(String)
    tempo_fila = Column(String)
    tempo_atendimento = Column(String)
    tempo_pendencia = Column(String)
    tmic = Column(String)
    tmia = Column(String)
    tipo_atendimento = Column(String)
    nivel_servico = Column(String)
    id_atendimento_referencia = Column(String)
    id_status_atendimento = Column(String)
    id_contato = Column(String)
    id_classificacao = Column(String)
    contato = Column(String)
    telefone = Column(String)
    cpf = Column(String)
    email = Column(String)
    matricula = Column(String)
    agente = Column(String)
    status = Column(String)
    descricao_caminho_completo = Column(String)
    servico = Column(String)
    tipo_integracao = Column(String)
    conta = Column(String)
    cpf_informado = Column(String)
    id_humor = Column(String)
    icone = Column(String)
    humor = Column(String)
    tag = Column(String)
    data_prim_msg_agente = Column(TIMESTAMP)
    data_ulti_msg_agente = Column(TIMESTAMP)
    data_prim_msg_auto = Column(TIMESTAMP)
    data_ulti_msg_auto = Column(TIMESTAMP)
    data_prim_msg_cliente = Column(TIMESTAMP)
    data_ulti_msg_cliente = Column(TIMESTAMP)
    qtd_cliente = Column(String)
    qtd_agente = Column(String)
    qtd_auto = Column(String)
    recorrencia = Column(String)
    descricao_observacao =  Column(String)
    contato_classificacao = Column(String)
