"""table_reports

Revision ID: 158247280b91
Revises: 
Create Date: 2024-06-13 09:44:11.958172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '158247280b91'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id_atendimento', sa.String(), nullable=False),
    sa.Column('data_entrada', sa.TIMESTAMP(), nullable=True),
    sa.Column('data_atendimento', sa.TIMESTAMP(), nullable=True),
    sa.Column('data_fila', sa.TIMESTAMP(), nullable=True),
    sa.Column('data_termino', sa.TIMESTAMP(), nullable=True),
    sa.Column('id_tipo_integracao', sa.String(), nullable=True),
    sa.Column('protocolo', sa.String(), nullable=True),
    sa.Column('externo', sa.String(), nullable=True),
    sa.Column('boleano_receptivo', sa.String(), nullable=True),
    sa.Column('tempo_fila', sa.String(), nullable=True),
    sa.Column('tempo_atendimento', sa.String(), nullable=True),
    sa.Column('tempo_pendencia', sa.String(), nullable=True),
    sa.Column('tmic', sa.String(), nullable=True),
    sa.Column('tmia', sa.String(), nullable=True),
    sa.Column('tipo_atendimento', sa.String(), nullable=True),
    sa.Column('nivel_servico', sa.String(), nullable=True),
    sa.Column('id_atendimento_referencia', sa.String(), nullable=True),
    sa.Column('id_status_atendimento', sa.String(), nullable=True),
    sa.Column('id_contato', sa.String(), nullable=True),
    sa.Column('id_classificacao', sa.String(), nullable=True),
    sa.Column('contato', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('matricula', sa.String(), nullable=True),
    sa.Column('agente', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('descricao_caminho_completo', sa.String(), nullable=True),
    sa.Column('servico', sa.String(), nullable=True),
    sa.Column('tipo_integracao', sa.String(), nullable=True),
    sa.Column('conta', sa.String(), nullable=True),
    sa.Column('cpf_informado', sa.String(), nullable=True),
    sa.Column('id_humor', sa.String(), nullable=True),
    sa.Column('icone', sa.String(), nullable=True),
    sa.Column('humor', sa.String(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('data_prim_msg_agente', sa.TIMESTAMP(), nullable=True),
    sa.Column('data_ulti_msg_agente', sa.TIMESTAMP(), nullable=True),
    sa.Column('data_prim_msg_auto', sa.TIMESTAMP(), nullable=True),
    sa.Column('data_ulti_msg_auto', sa.TIMESTAMP(), nullable=True),
    sa.Column('data_prim_msg_cliente', sa.TIMESTAMP(), nullable=True),
    sa.Column('data_ulti_msg_cliente', sa.TIMESTAMP(), nullable=True),
    sa.Column('qtd_cliente', sa.String(), nullable=True),
    sa.Column('qtd_agente', sa.String(), nullable=True),
    sa.Column('qtd_auto', sa.String(), nullable=True),
    sa.Column('recorrencia', sa.String(), nullable=True),
    sa.Column('descricao_observacao', sa.String(), nullable=True),
    sa.Column('contato_classificacao', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_atendimento')
    )
    op.create_index(op.f('ix_reports_id_atendimento'), 'reports', ['id_atendimento'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_id_atendimento'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
